### PR TITLE
v0.3.1 - Fix `PushManager.getSubscription` to allow it to return `null`.

### PR DESCRIPTION
**Pull request by gmpassos**

### CODE REVIEW

**Review by isoos — COMMENTED** [review]
Technically this is a breaking change and may warrant for a version of `0.4.0`. Do you have other changes planned?

**Comment by gmpassos** [comment]
Would you like me to modify the code or the version for merging?

**Comment by gmpassos** [comment]
@isoos, we really need this fix since it's not possible to catch the error when returning `null` due to the `promiseToFuture` process.

**Comment by isoos** [comment]
As long as @kevmoo is happy with the change and the new version (I have the repo under my account, but I'm not really involved in the development or usage/direction decisions.)

**Comment by gmpassos** [comment]
What are the next steps?

**Comment by gmpassos** [comment]
@isoos @kevmoo 

Sorry to bother, but this fix is quite simple and enables the correct use of push notifications. What are the next steps?

Thank you in advance.

Best regards.

**Review by kevmoo — APPROVED** [review]
Okay with me. I haven't touched this in a LONG time.

**Comment by gmpassos** [comment]
@kevmoo, would you mind publishing it at your earliest convenience?

Best regards.

**Comment by isoos** [comment]
@gmpassos: published

**Comment by isoos** [comment]
thanks for the PR and looking out for it!

**Comment by gmpassos** [comment]
Thanks. It has already been tested and deployed in production.

Best regards.

**Pull request merged**
